export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_SUMMARY_ERROR = 'FETCH_SUMMARY_ERROR';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const SET_COUNTRY_SEARCH_QUERY = 'SET_COUNTRY_SEARCH_QUERY';
export const SET_COUNTRY_SORTING_OPTION = 'SET_COUNTRY_SORTING_OPTION';
