export const SET_FAVORITES_COUNTRY_NAMES = 'SET_FAVORITES_COUNTRY_NAMES';
export const SET_FAVORITES_COUNTRIES_DATA = 'SET_FAVORITES_COUNTRIES_DATA';
export const SET_FAVORITES_LOADED = 'SET_FAVORITES_LOADED';
